version: "3.9"
services:
  db:
    image: db:0.0.1
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=top_secret
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && uvicorn app.asgi:application --host 0.0.0.0 --workers 4"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - POSTGRES_NAME=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=top_secret
      - POSTGRES_HOST=db
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=465
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
  web:
    image: nginx:latest
    ports:
      - 5000:80
      #- 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
