# Generated by Django 4.1 on 2022-09-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='report',
            field=models.UUIDField(),
        ),
    ]
