# Generated by Django 4.1 on 2022-09-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_transactions_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='report_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
